version: '3.8'

services:
  phaser-game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./cert.pem:/etc/nginx/ssl/cert.pem
      - ./fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./privkey.pem:/etc/nginx/ssl/privkey.pem
    restart: unless-stopped 