services:
  phaser-game:
    container_name: phaser-game-container
    image: burakyapici747/phaser-game:latest
    ports:
      - "443:443"
    volumes:
      - ./cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    restart: unless-stopped 