name: Deploy Phaser Game

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/phaser-game:latest

      - name: Copy configuration files to VDS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml,nginx.conf"
          target: "~/phaser-game"

      - name: Deploy to VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Create project directory if not exists
            mkdir -p ~/phaser-game
            cd ~/phaser-game

            # Copy SSL files
            echo "${{ secrets.CERT_PEM }}" > cert.pem
            echo "${{ secrets.FULLCHAIN_PEM }}" > fullchain.pem
            echo "${{ secrets.PRIVKEY_PEM }}" > privkey.pem

            # Deploy with docker compose
            sudo docker compose pull
            sudo docker compose down || true
            sudo docker compose up -d 