name: Deploy Phaser Game

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/phaser-game:latest

      - name: Copy SSL files and Deploy to VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Create project directory if not exists
            mkdir -p ~/phaser-game
            cd ~/phaser-game

            # Copy SSL files
            echo "${{ secrets.CERT_PEM }}" > cert.pem
            echo "${{ secrets.FULLCHAIN_PEM }}" > fullchain.pem
            echo "${{ secrets.PRIVKEY_PEM }}" > privkey.pem

            # Create or update docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            version: '3.8'
            services:
              phaser-game:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/phaser-game:latest
                ports:
                  - "${PORT:-8080}:8080"
                environment:
                  - PORT=8080
                volumes:
                  - ./cert.pem:/etc/nginx/ssl/cert.pem
                  - ./fullchain.pem:/etc/nginx/ssl/fullchain.pem
                  - ./privkey.pem:/etc/nginx/ssl/privkey.pem
                restart: unless-stopped
            EOL

            # Pull and deploy
            sudo docker compose pull
            sudo docker compose down || true
            sudo docker compose up -d 